### ISSUE TITLE
Change the "Offshore" label on thr figure from static to dynamic in ADM (Carbonate stratigraphy)

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/DarwinCAT#4]

**Comment by NiklasHohmann** [comment]
Changed title in admplot from "Offshore" to "from Shore". Resolved with [this commit](https://github.com/MindTheGap-ERC/DarwinCAT/commit/2bd3e202b0bb8f2e53d0b11f5251a9fd45cfeafe)
